-- =====================================================
-- Migration: Create ai_insights table
-- Description: Caches daily AI-generated insights about bed availability
-- =====================================================

-- Create ai_insights table
CREATE TABLE IF NOT EXISTS ai_insights (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    insight_text TEXT NOT NULL,
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for efficient active insight queries
-- Note: Removed WHERE predicate because NOW() is not IMMUTABLE
-- Filter will be applied in queries instead
CREATE INDEX IF NOT EXISTS idx_ai_insights_expires_at 
    ON ai_insights(expires_at DESC);

-- Create index for finding latest insight
CREATE INDEX IF NOT EXISTS idx_ai_insights_generated_at 
    ON ai_insights(generated_at DESC);

-- Enable Row Level Security
ALTER TABLE ai_insights ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Authenticated users can read active (non-expired) insights
CREATE POLICY "Authenticated users read active ai_insights"
    ON ai_insights FOR SELECT
    USING (
        auth.role() = 'authenticated' 
        AND expires_at > NOW()
    );

-- Add constraint: expires_at must be after generated_at
ALTER TABLE ai_insights 
    ADD CONSTRAINT chk_ai_insights_expires_after_generated 
    CHECK (expires_at > generated_at);

-- Add table and column comments
COMMENT ON TABLE ai_insights IS 'Cached AI-generated daily insights about hospital bed availability. Generated at 6:00 AM daily with 24h TTL';
COMMENT ON COLUMN ai_insights.insight_text IS 'AI-generated insight text (1-2 sentences) for display in Alert component';
COMMENT ON COLUMN ai_insights.generated_at IS 'When the insight was generated by Claude API';
COMMENT ON COLUMN ai_insights.expires_at IS 'When the insight expires (24h cache). Set to generated_at + 24 hours';

